### ISSUE TITLE
ImportError: No module named stem.util.system

### ISSUE THREAD

**Issue by MilkyWay90** [pannous/angle#6]
When I was running ./install.sh, it did this:

`INSTALLING DEPENDENCIES... This might take a minute or 10
Entering 'EnglishScript.tmbundle'
From https://github.com/pannous/EnglishScript.tmbundle
 * branch            master     -> FETCH_HEAD
Already up to date.
Entering 'kast'
From https://github.com/pannous/kast
 * branch            master     -> FETCH_HEAD
Already up to date.
Entering 'samples'
From https://github.com/pannous/english-script-samples
 * branch            master     -> FETCH_HEAD
Already up to date.
export ANGLE_HOME=/Users/neilsharma/angle
source ./install.sh
Password:
ln: /usr/local/bin/angle: File exists
Installing Python requirements
Requirement already satisfied: astor in /Users/neilsharma/anaconda2/lib/python2.7/site-packages (from -r requirements.txt (line 3)) (0.7.1)
Requirement already satisfied: dill in /Users/neilsharma/anaconda2/lib/python2.7/site-packages (from -r requirements.txt (line 4)) (0.2.8.2)
Requirement already satisfied: stem in /Users/neilsharma/anaconda2/lib/python2.7/site-packages (from -r requirements.txt (line 5)) (1.7.1)
Requirement already satisfied: pytest in /Users/neilsharma/anaconda2/lib/python2.7/site-packages (from -r requirements.txt (line 7)) (3.8.0)
Requirement already satisfied: nose in /Users/neilsharma/anaconda2/lib/python2.7/site-packages (from -r requirements.txt (line 8)) (1.3.7)
Requirement already satisfied: py>=1.5.0 in /Users/neilsharma/anaconda2/lib/python2.7/site-packages (from pytest->-r requirements.txt (line 7)) (1.6.0)
Requirement already satisfied: six>=1.10.0 in /Users/neilsharma/anaconda2/lib/python2.7/site-packages (from pytest->-r requirements.txt (line 7)) (1.11.0)
Requirement already satisfied: setuptools in /Users/neilsharma/anaconda2/lib/python2.7/site-packages (from pytest->-r requirements.txt (line 7)) (40.2.0)
Requirement already satisfied: attrs>=17.4.0 in /Users/neilsharma/anaconda2/lib/python2.7/site-packages (from pytest->-r requirements.txt (line 7)) (18.2.0)
Requirement already satisfied: more-itertools>=4.0.0 in /Users/neilsharma/anaconda2/lib/python2.7/site-packages (from pytest->-r requirements.txt (line 7)) (4.3.0)
Requirement already satisfied: atomicwrites>=1.0 in /Users/neilsharma/anaconda2/lib/python2.7/site-packages (from pytest->-r requirements.txt (line 7)) (1.2.1)
Requirement already satisfied: pluggy>=0.7 in /Users/neilsharma/anaconda2/lib/python2.7/site-packages (from pytest->-r requirements.txt (line 7)) (0.7.1)
Requirement already satisfied: funcsigs in /Users/neilsharma/anaconda2/lib/python2.7/site-packages (from pytest->-r requirements.txt (line 7)) (1.0.2)
Requirement already satisfied: pathlib2>=2.2.0 in /Users/neilsharma/anaconda2/lib/python2.7/site-packages (from pytest->-r requirements.txt (line 7)) (2.3.2)
Requirement already satisfied: scandir in /Users/neilsharma/anaconda2/lib/python2.7/site-packages (from pathlib2>=2.2.0->pytest->-r requirements.txt (line 7)) (1.9.0)
OK, now run ./bin/angle
Traceback (most recent call last):
  File "./bin/angle", line 10, in <module>
    from angle import english_parser
  File "./angle/__init__.py", line 16, in <module>
    import angle.english_parser 
  File "./angle/english_parser.py", line 12, in <module>
    import stem.util.system
`

**Comment by jayvdb** [comment]
The dependency https://pypi.org/project/stem/ doesnt look right.
